### ISSUE TITLE
Would you be able to add a LICENSE file?

### ISSUE THREAD

**Issue by silviapfeiffer** [dscape/cycle#22]
Sorry to be pedantic, but it would be helpful if there was an explicit LICENSE on the repo.

**Comment by dscape** [comment]
see #19 #18 #1 #2 #5 #8 #9 #10 #11 #12 #15 #16

**Comment by silviapfeiffer** [comment]
😀 my request still stands, but I understand your reasons

**Comment by dscape** [comment]
Not my code — if your legal department is not pedantic this is "Public domain"

**Comment by silviapfeiffer** [comment]
:-)
